### ISSUE TITLE
aesthetic issues in the panels?

### ISSUE THREAD

**Issue by squinkylabs** [kockie69/RPJ#19]
There are clearly numerous things about the layout of these panels that look unintentional. I assume if you wanted to spend the time to make everything "neat and tidy" you could perfectly well do it, so I won't log a bunch of specific issues about it. But if you would ever like to to do so, or test some future plugin, I would be happy to.

**Comment by squinkylabs** [comment]
Grendel is the most polished, but has numerous alignment issues:

![image](https://user-images.githubusercontent.com/16314838/136735020-c4528a9d-ea32-4af9-a9f2-dbbe6ea84c69.png)

The RED LED are not centered in their columns. The are maybe one or two pixels too far left.
The knobs are not centered between the scales around them. they are slightly to the left.
The jacks are not centered at all in their columns. The look like they are several pixels too far left.

**Comment by squinkylabs** [comment]
Also the block colums are not the same height. The one on the far right maybe extends farther than the other ones:
![image](https://user-images.githubusercontent.com/16314838/136735359-616937d5-1f3c-4377-984c-065faab542d0.png)

**Comment by squinkylabs** [comment]
The switch labels in circular ride are wonky in v2:

![image](https://user-images.githubusercontent.com/16314838/136735570-a1c701ce-b548-4a5a-80f7-3b275e9b650d.png)

At smaller zoom level that text with the reduced intercharacter spacing is difficult to read, and look broken.

**Comment by kockie69** [comment]
I am redesigning at the moment:
![image](https://user-images.githubusercontent.com/2545165/137588938-94f1f55d-c5be-41e5-8f47-de4c9b913b99.png)

**Comment by kockie69** [comment]
I think it is much better. By the way, the red, white and blue are according to the Dutch Flag. The green that I am using is from the flag from the area I come from. I am now aligning everything by Inkscape which works much better.

**Comment by squinkylabs** [comment]
ooh, that looks really nice!

**Comment by kockie69** [comment]
Completely redone the styling. I will close this one for now.
