### ISSUE TITLE
Panel fails to load on Linux

### ISSUE THREAD

**Issue by cschol** [kockie69/RPJ#20]
```
[1.099 warn src/window/Svg.cpp:112 load] Failed to load SVG /Rack-2.0-Home/plugins/RPJ/res/TuxOn.svg
```

The file in the repository is called `Tuxon.svg`, which causes problems on platforms with case-sensitive file systems.

**Comment by kockie69** [comment]
Changed the name in git and pushed

**Comment by cschol** [comment]
Works. Thanks.
