### ISSUE TITLE
FR: Circular Ride v2 improvement suggestions

### ISSUE THREAD

**Issue by fractalgee** [kockie69/RPJ#22]
This is a feature request to add a sync/clock input to Circular Ride so it can be easily synced

**Comment by kockie69** [comment]
I have built in sync. First test look positive. 
If you build from this repo can you test it for me?

https://github.com/kockie69/RPJ/tree/FR-Issue-22

**Comment by fractalgee** [comment]
That works! thanks. Now, how about some CV ins over all those knobs? CV all
the things is a good mantra in modular after all...No rush of course, but
now i want to modulate the delay times lol.....at least, the rest could
also be good as sound design tools.....

Anyhow. They look great, seem to work as advertised so great job on this!

Thanks!

**Comment by kockie69** [comment]
I can add the cv's to the delays, although I think that will create some probably unwanted side effects. But let me add that and see where we go from there

**Comment by fractalgee** [comment]
Sounds good. It is just always good to have CV control over any of the things (of course stoermelder mapping tools to rescue if not) but modular is made to CV after all.....

**Comment by kockie69** [comment]
New version available with cv's for delay params. 

https://github.com/kockie69/RPJ/tree/FR-Issue-22

**Comment by fractalgee** [comment]
As Omar would say, Proper!

nice one, think about the others too, feedback for example and
dry/wet/lpf/hpf would also be cool. still space on that panel ;)

lovely. Makes me miss the Chronoblob2 less :D

**Comment by kockie69** [comment]
Yes, let me work on that. Maybe a bit of promotion on this module might help too ;-)
Next what I wanted to do next is add more algorithms. But let me add the cv's first.

**Comment by kockie69** [comment]
OK, all cv's are implemented. Have a look and let me know your thoughts.....

**Comment by fractalgee** [comment]
Seems to work fine and looks good. thanks! Will play more next days, but no issues thus far, am currently modulating center delay time for nice slow evolving effect. Will work on a patch promoting this one, as it stars to work just like the Chronoblob2 in ping-pong and normal mode. Very cool, I can live with this as a replacement just fine

**Comment by kockie69** [comment]
I will close this issue for now. If you experience any issues during your test feel free to raise a new issue.

**Comment by fractalgee** [comment]
all good, thanks

**Comment by fractalgee** [comment]
BTW, Omri Cohen wants to test it ;) so I did promote it a bit  Can I give him my build? Or will you make a win build for him? If you are OK I can give him my build to test

**Comment by kockie69** [comment]
You can give him your build, no problem. Thanks for promoting this!

Op zo 21 nov. 2021 om 20:12 schreef fractalgee ***@***.***>:

**Comment by kockie69** [comment]
I have made a small update. The parameters for the filters (LPF/HPF)  were not optimal, this has been improved now. You might want to give Omri an updated version if he is also testing the LCRDelay.

https://github.com/kockie69/RPJ/tree/v2

**Comment by fractalgee** [comment]
ok, will do, rebuilding shortly after fresh pull

**Comment by fractalgee** [comment]
no issues so all good as far as I can tell, loving the Circular Ride
Sent the updated build to Omri as well

**Comment by fractalgee** [comment]
2.0.4's and 2.0.3's filters don't do a thing I am sad to report. Hope
nothing too major that needs fixing.... Just confirmed with scope and
oscilloscope that indeed, sound does not change if knobs turned and/or CV
is fed in....  Both LPF and HPF have that issue Do I need to send audio
through those CV ins? Not tried that I just realized when I tested earlier

**Comment by fractalgee** [comment]
In case that gets misread, Circular Ride's LPF/HPF

**Comment by kockie69** [comment]
They only work with the LCRDelay algorithm. Have you selected that one?
I tried it and of course it is working for me (like always ;-)).

**Comment by fractalgee** [comment]
Seems odd they are only working with the newly added one, any way to also
get em to work in all the others (that are there and/or the ones you are
planning to add?

**Comment by kockie69** [comment]
The point is that I implement ' standard' algorithms and the first two don't have filtering in their feedback so that's not implemented. But maybe I have to say (kind of by default) every feedback will have filtering which for the user is much more clear. Agree. Ok, nice improvement for tonight.

**Comment by fractalgee** [comment]
Excellent, thanks for listening, Omri also found the filters not working in
the standard algos, so he wasn't too impressed by what I got.
We are all in this together after all, and collaboration is much better
than competition any time in my book.

**Comment by fractalgee** [comment]
a couple of things:

If I switch to the new delay type the letters in the display run
together, so it is impossible to read what algo is active. That display
issue needs fixing.

Also, if I touch the LPF knb when I have Caudal out #3 connected to it's CV
it goes into overload on the mixer until I turn mixer level down (master!)
works after that to set it back up to where it was. glitches sometimes when
I move any knob. so seems it's not fading from one to next value, might
also be handy

**Comment by fractalgee** [comment]
Spoke too soon, even worse, it is stuck in full out, and the comp is
squashing it 100% hence no sound. Switch back to PingPong and sound returns

**Comment by kockie69** [comment]
I think/hope I already fixed that LPF issue as I spotted an error when I started looking at the code to work on the filters. I need to test it but I will get back to you on that when the filters are implemented for all the algos.
The point with the display letters, you are not on windows are you? As I only have windows to test and I have never seen this happen before and I am reusing that code for all my displays.

**Comment by fractalgee** [comment]
I am on windows, here is what it looks like at full zoom

**Comment by fractalgee** [comment]
Here is what it looks like at 100% zsoom, 150 is no better. The other two algos show fine. I am on Windows 10
![image_2021-11-23_193633](https://user-images.githubusercontent.com/12473856/143083943-e73d72ce-4567-4987-880e-c19884c40c20.png)

**Comment by kockie69** [comment]
This says LCRDelay, nothing wrong :-) But I will change the spacing so it will be less compact

**Comment by fractalgee** [comment]
yes, it was just too squashed (and I am getting older ;) )

**Comment by kockie69** [comment]
https://github.com/kockie69/RPJ/tree/issue-29

Can you check this one? I think this one does what we want.

**Comment by fractalgee** [comment]
OK, built and briefly tested on current patch. Seems to do something now
but need to work out in scope/oscilloscope what effect it now has. Tomorrow
for that though.

**Comment by fractalgee** [comment]
OK, did you actually push those changes? Seems to still be non-functional filter-wise, the rest seems OK as far as I can tell. But one can twiddle the LPF/HPF knobs at will and sound does not change coming out of Circular Ride, waveform on oscilloscope also does not change, so no filtering seems to take place. Also tried the new algo, still get no response from filters...

**Comment by kockie69** [comment]
They are pushed into issue-29 branch (https://github.com/kockie69/RPJ/tree/issue-29), so make sure you are building that one it is not (yet) on the v2 .
Also, the filters are only in the feedback, so without feedback you will see no effect (and of course make sure you have them enabled in the menu)

**Comment by fractalgee** [comment]
aha! Okidoki, retesing and yes, I built that branch, so should have all the
fixes. My bad, that was a misunderstanding on my part.

**Comment by fractalgee** [comment]
Alright, that works nicely! 

Merge back to v2 branch at will and make a new build when you have time please. As the Chronoblob also has a beta release since early this morning my time ;)

**Comment by kockie69** [comment]
That is all done. We now have a v2.0.5 which includes the latest CircularRide.

**Comment by fractalgee** [comment]
That LCR Delay algo is the bee's knees! I have CR now fading in and out, sometimes providing bursts of delays and the Chronoblob in default send delay duty. Lovey that. Great stuff. Thanks again!
