### ISSUE TITLE
Built in tooltips don't work in the "wave" and "stepping" controls

### ISSUE THREAD

**Issue by kockie69** [kockie69/RPJ#40]
It's too bad that the VCV built in tooltips don't work in the "wave" and "stepping" controls. the tooltips on the - and + buttons are... not very helpful. Esp on that stepping control it would be nice to know that those values mean.

**Comment by squinkylabs** [comment]
I logged a bug about this, unfortunately in the other repo (https://github.com/kockie69/SquinkyVCV-main/issues/56). I was noting that Vult does not use +/- buttons to select one of they - they usually use a three position toggle. Looking in the code verifies the obvious - this module uses two params, one for up and one for down. Which is going to make tooptips problematic and they are per param.

Also, using two param widgets makes the Midi Mapper work strangely, In this illo you can see a three position toggle maps just fine to one midi control. But with plink you need to map both the up and the down button, whereas most people, if they did this, would expect to be able to use a knob on a midi controller to go through all three values. You can sort of see it in this screen grab>

Of course all these issue (tooltip, midi mapping) come from using two params and two param widgets. It seems like to really fix this "correctly" you would need to code a param widget from scratch that has the two buttons and the display, but all attached to a single param. Or use the three position toggle like Vult does - it will "just work", and is much more like real hardware than any of the other alternatives.

fwiw, most people don't use this mapping feature, but I have certainly gotten bug reports in the past when I've broken it. Esp once the Stoermeler plugins come out for V2.

![image](https://user-images.githubusercontent.com/16314838/149842916-8b1d3132-56f1-414f-a006-731ea68ff2a4.png)

**Comment by kockie69** [comment]
I close this one, as the mapping works as I want it. You can map to either the + or - button and by pressing button on your device it will scroll through the menu.
