### ISSUE TITLE
Bypass for Pigeon Plink

### ISSUE THREAD

**Issue by mosesve** [kockie69/RPJ#41]
It would be nice to add the new bypass-feature to pass through the Input present at LFM to the audio output without any alteration.
That way it would be much easier to check the output of a modulator in a FM-Chain.

**Comment by kockie69** [comment]
This is done, will be part of the next release (or in first release if we are lucky)

**Comment by mosesve** [comment]
Awesome. The more I play with it, the more awesome it gets... 
I have a few new Module Selections Ready... an "Additive Sine Voice", a "5 Voice 3-Oscillator Polysynth" with one PP (Prophet 101 anyone?) and a "Synced FM-Lead" with tons of different timbres... Maybe i get a second video ready soon.
