### ISSUE TITLE
Remove dist directory from repository

### ISSUE THREAD

**Issue by cschol** [kockie69/RPJ#5]
One more issue I noticed is that the `dist` directory is committed to the repository.

To support an efficient build process on the Rack build system, which clones the repository on build, please remove the `dist` directory from the repository **and its history**.

See [BFG Repo Cleaner](https://rtyley.github.io/bfg-repo-cleaner/) for a way to remove the `dist` directory from the repo history.

**Just removing the `dist` directory with a commit is NOT ENOUGH.**

**Comment by kockie69** [comment]
Removed both .vscode and dist with BFG
