### ISSUE TITLE
the changelog stops at 1.x, never gets to 2

### ISSUE THREAD

**Issue by squinkylabs** [kockie69/RPJ#58]
I don't remember what the "current" branch is here, so I may be wrong. The default branch is `main`, but I also looked on `v2`. It doesn't seem like either have been updated in a really long time. The one linked from the library version stops at 1.x also. Maybe you should remove the link from the plugin.json if you don't intend on updating it?

**Comment by kockie69** [comment]
In the next release changelog is picked up/updated
