### ISSUE TITLE
Both modules LFM crashes Rack - macos/Mojave

### ISSUE THREAD

**Issue by nay-seven** [kockie69/RPJ#71]
Hello,
here are my logs when trying to add both modules
both crash Mac book pro Mojave
[log.txt](https://github.com/kockie69/RPJ/files/9716688/log.txt)

**Comment by kockie69** [comment]
Thank you for logging this. Looks like something went wrong with the Mac build as I received a similar issue.

**Comment by nay-seven** [comment]
hello, i have tried to compile on my other machine, mac mini /mojave
failed, here the terminal log
[visualizer compil error.rtf.zip](https://github.com/kockie69/RPJ/files/9738678/visualizer.compil.error.rtf.zip)

**Comment by kockie69** [comment]
Hello, thanks for trying to compile yourself. As you might be aware, this module is using another project (projectM) so the first step of the build process is building that project. Their latest version is not building at the moment for Mac, so as a result mine will fail too. To solve this, I have changed my process, so it will pick up an older version of their code, which builds again for me.
You might give it a try, or wait until I have fixed it.

**Comment by nay-seven** [comment]
ok, i understand, 
thanks for the info

**Comment by kockie69** [comment]
You can try rhis version if you want:

[Mac-2.1.2 (9).zip](https://github.com/kockie69/RPJ/files/9738792/Mac-2.1.2.9.zip)

**Comment by nay-seven** [comment]
Yes !
both open! and looks stable
now need to test more cause not sure that it reacts correctly to audio input
will tell you
thanks

**Comment by kockie69** [comment]
Version 2.1.0 sent to VCV for deploy
